replicaCount: 1

image:
  repository: monishanelson/devsecops_accelerator
  pullPolicy: IfNotPresent
  tag: v1

annotations:
   name: express-app

service:
  type: ClusterIP
  port: 4000
  name: http
  protocol: TCP
  targetPort: http

resources: 
  limits:
     cpu: 500m
     memory: 512Mi
  requests:
     cpu: 100m
     memory: 128Mi

imagePullSecrets:
  - name: my-registry-secret
nameOverride: ""
fullnameOverride: ""

livenessProbe:
  httpGet:
    path: /
    port: http
    
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80





